unpackaged/main/default/objects/Account/fields/Ultimate_Parent__c.field-meta.xml
<CustomField>
    <fullName>Ultimate_Parent__c</fullName>
    <formula>IF(NOT(ISBLANK(Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Id)), Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Id,
IF(NOT(ISBLANK(Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Id)), Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Id,
IF(NOT(ISBLANK(Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Id)), Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Id,
IF(NOT(ISBLANK(Parent.Parent.Parent.Parent.Parent.Parent.Parent.Id)), Parent.Parent.Parent.Parent.Parent.Parent.Parent.Id,
IF(NOT(ISBLANK(Parent.Parent.Parent.Parent.Parent.Parent.Id)), Parent.Parent.Parent.Parent.Parent.Parent.Id,
IF(NOT(ISBLANK(Parent.Parent.Parent.Parent.Parent.Id)), Parent.Parent.Parent.Parent.Parent.Id,
IF(NOT(ISBLANK(Parent.Parent.Parent.Parent.Id)), Parent.Parent.Parent.Parent.Id,
IF(NOT(ISBLANK(Parent.Parent.Parent.Id)), Parent.Parent.Parent.Id,
IF(NOT(ISBLANK(Parent.Parent.Id)), Parent.Parent.Id,
IF(NOT(ISBLANK(Parent.Id)),Parent.Id,
Id))))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ultimate Parent</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Ultimate_Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Ultimate_Parent_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>a reference to the top most Account in the hierarchy based on the record given on the &quot;Account Name&quot; field.</description>
    <label>Ultimate Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/PopulateUltimateParentUpdateTest.cls
/**
@description - PopulateUltimateParentUpdateTest
@author Kharla Haldos
@date  July 11, 2016
@history Kharla Haldos July 11, 2016 - Test Class for PopulateUltimateParentContactBatchableTest and its negative scneario
**/


@isTest
public class PopulateUltimateParentUpdateTest {

     /*private static testmethod void PopulateUltimateParentUpdateSchedulableTest(){
        
        Test.startTest();
        system.schedule('PopulateUltimateParentContactBatchable', '0 0 23 **?', new PopulateUltimateParentContactSchedulable());
        
        Test.stopTest();
    }*/
    
    private static testMethod void PopulateUltimateParentContactBatchableTest() 
    {
        //Parent Account test data
        Account Acc1 = new Account();
        Acc1.Name = 'Test1';
        insert Acc1;
        
        //child Account test data
        Account Acc2 = new Account();
        Acc2.Name = 'Test2';        
        Acc2.ParentId = Acc1.id;
        
        insert Acc2;
        
        //test data for contact
        Contact con1 = new Contact();
        con1.LastName ='ConTest1';
        con1.AccountId = Acc2.id;

        insert con1;
        
        //Setting up the values of account fields to contact fields
        con1.Ultimate_Parent_Account__c = acc2.Ultimate_Parent__c;
        update con1;
             
                
       Test.startTest();
       Database.executebatch(new PopulateUltimateParentContactBatchable());
       Test.stopTest();     
        
       
    }       

    private static testMethod void PopulateUltimateParentContactBatchableTestNeg() 
    {
        
        //Parent Account test data
        Account Acc1 = new Account();
        Acc1.Name = 'Test1';
        insert Acc1;
        
        //Child Account test data
        Account Acc2 = new Account();
        Acc2.Name = 'Test2';        
        Acc2.ParentId = Acc1.id;
        
        insert Acc2;
        
        Contact con1 = new Contact();
        
        //Setting up the values of account fields to contact fields
        con1.Ultimate_Parent_Account__c = Acc1.id;
        update con1;
             
                
       Test.startTest();
       Database.executebatch(new PopulateUltimateParentContactBatchable());
       Test.stopTest();     
        
       
    }  
}