unpackaged/main/default/objects/Account/fields/Ultimate_Parent__c.field-meta.xml
<CustomField>
    <fullName>Ultimate_Parent__c</fullName>
    <formula>IF(NOT(ISBLANK(Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Id)), Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Id,
IF(NOT(ISBLANK(Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Id)), Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Id,
IF(NOT(ISBLANK(Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Id)), Parent.Parent.Parent.Parent.Parent.Parent.Parent.Parent.Id,
IF(NOT(ISBLANK(Parent.Parent.Parent.Parent.Parent.Parent.Parent.Id)), Parent.Parent.Parent.Parent.Parent.Parent.Parent.Id,
IF(NOT(ISBLANK(Parent.Parent.Parent.Parent.Parent.Parent.Id)), Parent.Parent.Parent.Parent.Parent.Parent.Id,
IF(NOT(ISBLANK(Parent.Parent.Parent.Parent.Parent.Id)), Parent.Parent.Parent.Parent.Parent.Id,
IF(NOT(ISBLANK(Parent.Parent.Parent.Parent.Id)), Parent.Parent.Parent.Parent.Id,
IF(NOT(ISBLANK(Parent.Parent.Parent.Id)), Parent.Parent.Parent.Id,
IF(NOT(ISBLANK(Parent.Parent.Id)), Parent.Parent.Id,
IF(NOT(ISBLANK(Parent.Id)),Parent.Id,
Id))))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Ultimate Parent</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Ultimate_Parent_Account__c.field-meta.xml
<CustomField>
    <fullName>Ultimate_Parent_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>a reference to the top most Account in the hierarchy based on the record given on the &quot;Account Name&quot; field.</description>
    <label>Ultimate Parent Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contacts</relationshipLabel>
    <relationshipName>Contacts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/PopulateUltimateParentContactBatchable.cls
/**
@description - PopulateUltimateParentUpdateTest
@author Kharla Haldos
@date  July 11, 2016
@history Kharla Haldos July 11, 2016 - Class for PopulateUltimateParentContactBatchableTest 
**/

global class PopulateUltimateParentContactBatchable implements Database.Batchable<sObject>
{
    //Query Locator - Retrieved all contacts records
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        return Database.getQueryLocator([SeLect Id, Name, AccountId, Ultimate_Parent_Account__c, Account.Ultimate_Parent__c from Contact WHERE AccountId != NULL]);
    }
    
    //Actual execution and logics
    global void execute(Database.BatchableContext BC, List<Contact> scope)
    {
        //Setting up the variables
        Set<Id> accIdSets = new Set<Id>();
        List<Account> accList = new List<Account>();
        
         for(Contact con: scope)
         {
             accIdSets.add(con.AccountId);
         }
        
        //Collate all accounts related to contacts ids
        if(!accIdSets.isEmpty())
        {
                    accList = [SELECT Id, Name, Ultimate_Parent__c from Account WHERE Id= :accIdSets];
        }
  
        if(acclist.size() > 0)
        {
    
            for(Contact con: scope)
            {
                for(Account acc: accList)
                {
                    if(con.AccountId == acc.id)
                    {
                        
                        if(acc.Ultimate_Parent__c != NULL)
                        {
                          //Populate the value of Account Ultimate Parent from contact Ultimate Parent Account
                          con.Ultimate_Parent_Account__c = acc.Ultimate_Parent__c;
                          
                        }
                    }
                }
            
            }
            
        
           Database.Update(scope);

         
        }    
    }
    
    global void finish(Database.BatchableContext BC)
    {
    
    }

}